-- Oracle init aligned with application-k8s.yaml:
--   spring.datasource.dynamic.datasource.master.connection-init-sql:
--     ALTER SESSION SET CURRENT_SCHEMA = ${DB_SCHEMA:jasolar_budget}
-- App typically connects as SYSTEM (password from DB_PASSWORD in real env; local Docker often Oracle123).
-- This script creates user/schema JASOLAR_BUDGET and base tables from the user-provided DDL summary.
--
-- Run (example, local Oracle Free in Docker):
--   docker exec -i oracle-free sqlplus -s system/Oracle123@//localhost:1521/FREEPDB1 @/tmp/001_jasolar_budget_tables.sql
-- Or copy into container first: docker cp ... oracle-free:/tmp/

SET DEFINE OFF
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

-- ========== 1) Schema user (Oracle schema = user) ==========
BEGIN
  EXECUTE IMMEDIATE 'DROP USER jasolar_budget CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1918 THEN RAISE; END IF; -- ORA-01918: user does not exist
END;
/

CREATE USER jasolar_budget IDENTIFIED BY "Oracle123"
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS
  TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE, CREATE VIEW TO jasolar_budget;

-- ========== 2) Tables (owned by JASOLAR_BUDGET) ==========
ALTER SESSION SET CURRENT_SCHEMA = JASOLAR_BUDGET;

CREATE TABLE "SYSTEM_ORGANIZATION"
(
   "ID"                 NUMBER(19,0)         NOT NULL,
   "ORG_CODE"           VARCHAR2(128 CHAR),
   "ORG_NAME"           VARCHAR2(128 CHAR),
   "PARENT_ORG_CODE"    VARCHAR2(128 CHAR),
   "CREATOR"            VARCHAR2(128 CHAR),
   "CREATE_TIME"        TIMESTAMP,
   "UPDATER"            VARCHAR2(128 CHAR),
   "UPDATE_TIME"        TIMESTAMP,
   "DELETED"            NUMBER(1,0),
   CONSTRAINT PK_SYSTEM_ORGANIZATION PRIMARY KEY ("ID")
);

CREATE TABLE "SYSTEM_MANAGEMENT_ORGANIZATION"
(
   "ID"               NUMBER(19,0)      NOT NULL,
   "ORG_CODE"         VARCHAR2(128 CHAR),
   "DEPT_CODE"        VARCHAR2(128 CHAR),
   "MORG_CODE"        VARCHAR2(128 CHAR),
   "MORG_NAME"        VARCHAR2(128 CHAR),
   "PARENT_MORG_CODE" VARCHAR2(128 CHAR),
   "EHR_CODE"         VARCHAR2(128 CHAR),
   "IS_LEAF"          NUMBER(1,0),
   "EFFECTIVE_START"  TIMESTAMP,
   "EFFECTIVE_END"    TIMESTAMP,
   "CREATOR"          VARCHAR2(128 CHAR),
   "CREATE_TIME"      TIMESTAMP,
   "UPDATER"          VARCHAR2(128 CHAR),
   "UPDATE_TIME"      TIMESTAMP,
   "DELETED"          NUMBER(1,0),
   CONSTRAINT "PK_SYSTEM_MANAGEMENT_ORGANIZAT" PRIMARY KEY ("ID")
);

CREATE TABLE "SYSTEM_PROJECT"
(
   "ID"                 NUMBER(19,0)         NOT NULL,
   "PROJECT_CODE"       VARCHAR2(128 CHAR),
   "PROJECT_NAME"       VARCHAR2(128 CHAR),
   "PARENT_PROJECT_CODE" VARCHAR2(128 CHAR),
   "IS_LEAF"            NUMBER(1,0),
   "CREATOR"            VARCHAR2(128 CHAR),
   "CREATE_TIME"        TIMESTAMP,
   "UPDATER"            VARCHAR2(128 CHAR),
   "UPDATE_TIME"        TIMESTAMP,
   "DELETED"            NUMBER(1,0),
   CONSTRAINT PK_SYSTEM_PROJECT PRIMARY KEY ("ID")
);

CREATE TABLE "BUDGET_LEDGER"
(
   "ID"                 NUMBER(19,0)         NOT NULL,
   "BIZ_TYPE"           VARCHAR2(128 CHAR),
   "BIZ_CODE"           VARCHAR2(128 CHAR),
   "BIZ_ITEM_CODE"      VARCHAR2(128 CHAR),
   "EFFECT_TYPE"        VARCHAR2(128 CHAR),
   "YEAR"               VARCHAR2(128 CHAR),
   "MONTH"              VARCHAR2(128 CHAR),
   "ACTUAL_YEAR"        VARCHAR2(128 CHAR),
   "ACTUAL_MONTH"       VARCHAR2(128 CHAR),
   "MORG_CODE"          VARCHAR2(128 CHAR),
   "BUDGET_SUBJECT_CODE" VARCHAR2(128 CHAR),
   "MASTER_PROJECT_CODE" VARCHAR2(128 CHAR),
   "ERP_ASSET_TYPE"     VARCHAR2(128 CHAR),
   "IS_INTERNAL"        VARCHAR2(128 CHAR),
   "CURRENCY"           VARCHAR2(128 CHAR),
   "AMOUNT"             NUMBER(17,2),
   "AMOUNT_CONSUMED_Q_ONE"   NUMBER(17,2),
   "AMOUNT_CONSUMED_Q_TWO"   NUMBER(17,2),
   "AMOUNT_CONSUMED_Q_THREE" NUMBER(17,2),
   "AMOUNT_CONSUMED_Q_FOUR"  NUMBER(17,2),
   "AMOUNT_AVAILABLE"        NUMBER(17,2),
   "METADATA"           CLOB,
   "VERSION"            VARCHAR2(128 CHAR),
   "VERSION_PRE"        VARCHAR2(128 CHAR),
   "CREATOR"            VARCHAR2(128 CHAR),
   "CREATE_TIME"        TIMESTAMP,
   "UPDATER"            VARCHAR2(128 CHAR),
   "UPDATE_TIME"        TIMESTAMP,
   "DELETED"            NUMBER(1,0),
   CONSTRAINT PK_BUDGET_LEDGER PRIMARY KEY ("ID")
);

CREATE TABLE "BUDGET_LEDGER_HEAD"
(
   "ID"                 NUMBER(19,0)         NOT NULL,
   "BIZ_TYPE"           VARCHAR2(128 CHAR),
   "BIZ_CODE"           VARCHAR2(128 CHAR),
   "DOCUMENT_NAME"      VARCHAR2(256 CHAR),
   "DATA_SOURCE"        VARCHAR2(64 CHAR),
   "VERSION"            VARCHAR2(128 CHAR),
   "STATUS"             VARCHAR2(128 CHAR),
   "CREATOR"            VARCHAR2(128 CHAR),
   "CREATE_TIME"        TIMESTAMP,
   "UPDATER"            VARCHAR2(128 CHAR),
   "UPDATE_TIME"        TIMESTAMP,
   "DELETED"            NUMBER(1,0),
   CONSTRAINT PK_BUDGET_LEDGER_HEAD PRIMARY KEY ("ID")
);

CREATE TABLE "BUDGET_BALANCE"
(
   "ID"                 NUMBER(19,0)         NOT NULL,
   "POOL_ID"            NUMBER(19,0),
   "QUOTA_ID"           NUMBER(19,0),
   "MORG_CODE"          VARCHAR2(128 CHAR),
   "PROJECT_CODE"       VARCHAR2(128 CHAR),
   "CUSTOM_CODE"        VARCHAR2(128 CHAR),
   "ACCOUNT_SUBJECT_CODE" VARCHAR2(128 CHAR),
   "ERP_ASSET_TYPE"     VARCHAR2(128 CHAR),
   "IS_INTERNAL"        VARCHAR2(128 CHAR),
   "YEAR"               VARCHAR2(128 CHAR),
   "QUARTER"            VARCHAR2(128 CHAR),
   "CURRENCY"           VARCHAR2(128 CHAR),
   "VERSION"            VARCHAR2(128 CHAR),
   "AMOUNT_FROZEN"      NUMBER(17,2),
   "AMOUNT_FROZEN_VCHANGED" NUMBER(17,2),
   "AMOUNT_OCCUPIED"    NUMBER(17,2),
   "AMOUNT_OCCUPIED_VCHANGED" NUMBER(17,2),
   "AMOUNT_ACTUAL"      NUMBER(17,2),
   "AMOUNT_ACTUAL_VCHANGED" NUMBER(17,2),
   "AMOUNT_AVAILABLE"   NUMBER(17,2),
   "AMOUNT_AVAILABLE_VCHANGED" NUMBER(17,2),
   "AMOUNT_PAY_AVAILABLE" NUMBER(17,2),
   "AMOUNT_PAY_AVAILABLE_VCHANGED" NUMBER(17,2),
   "CREATOR"            VARCHAR2(128 CHAR),
   "CREATE_TIME"        TIMESTAMP,
   "UPDATER"            VARCHAR2(128 CHAR),
   "UPDATE_TIME"        TIMESTAMP,
   "DELETED"            NUMBER(1,0),
   CONSTRAINT PK_BUDGET_BALANCE PRIMARY KEY ("ID")
);

CREATE TABLE "BUDGET_QUOTA"
(
   "ID"                 NUMBER(19,0)         NOT NULL,
   "POOL_ID"            NUMBER(19,0),
   "MORG_CODE"          VARCHAR2(128 CHAR),
   "PROJECT_CODE"       VARCHAR2(128 CHAR),
   "CUSTOM_CODE"        VARCHAR2(128 CHAR),
   "ACCOUNT_SUBJECT_CODE" VARCHAR2(128 CHAR),
   "ERP_ASSET_TYPE"     VARCHAR2(128 CHAR),
   "IS_INTERNAL"        VARCHAR2(128 CHAR),
   "YEAR"               VARCHAR2(128 CHAR),
   "QUARTER"            VARCHAR2(128 CHAR),
   "BUDGET_TYPE"        VARCHAR2(128 CHAR),
   "CURRENCY"           VARCHAR2(128 CHAR),
   "VERSION"            VARCHAR2(128 CHAR),
   "AMOUNT_TOTAL"       NUMBER(18,6),
   "AMOUNT_TOTAL_VCHANGED" NUMBER(18,6),
   "AMOUNT_ADJ"         NUMBER(18,6),
   "AMOUNT_PAY"         NUMBER(18,6),
   "AMOUNT_PAY_VCHANGED" NUMBER(18,6),
   "CREATOR"            VARCHAR2(128 CHAR),
   "CREATE_TIME"        TIMESTAMP,
   "UPDATER"            VARCHAR2(128 CHAR),
   "UPDATE_TIME"        VARCHAR2(128 CHAR),
   "DELETED"            NUMBER(1,0),
   CONSTRAINT PK_BUDGET_QUOTA PRIMARY KEY ("ID")
);

CREATE TABLE "BUDGET_POOL_DEM_R"
(
   "ID"                 NUMBER(19,0)         NOT NULL,
   "YEAR"               VARCHAR2(4 CHAR),
   "QUARTER"            VARCHAR2(16 CHAR),
   "MORG_CODE"          VARCHAR2(128 CHAR),
   "BUDGET_SUBJECT_CODE" VARCHAR2(128 CHAR),
   "MASTER_PROJECT_CODE" VARCHAR2(128 CHAR),
   "ERP_ASSET_TYPE"     VARCHAR2(128 CHAR),
   "IS_INTERNAL"        VARCHAR2(128 CHAR),
   "CREATOR"            VARCHAR2(128 CHAR),
   "CREATE_TIME"        TIMESTAMP,
   "UPDATER"            VARCHAR2(128 CHAR),
   "UPDATE_TIME"        TIMESTAMP,
   "DELETED"            NUMBER(1,0),
   CONSTRAINT PK_BUDGET_POOL_DEM_R PRIMARY KEY ("ID")
);

CREATE TABLE "BUDGET_PERIOD"
(
   "ID"                 NUMBER(19,0)         NOT NULL,
   "YEAR"               VARCHAR2(128 CHAR),
   "MONTH"              VARCHAR2(128 CHAR),
   "PERIOD_TYPE"        VARCHAR2(128 CHAR),
   "START_DATE"         TIMESTAMP,
   "END_DATE"           TIMESTAMP,
   "CREATOR"            VARCHAR2(128 CHAR),
   "CREATE_TIME"        TIMESTAMP,
   "UPDATER"            VARCHAR2(128 CHAR),
   "UPDATE_TIME"        TIMESTAMP,
   "DELETED"            NUMBER(1,0),
   CONSTRAINT PK_BUDGET_PERIOD PRIMARY KEY ("ID")
);

CREATE TABLE "BUDGET_API_REQUEST_LOG"
(
   "ID"                 NUMBER(19,0)         NOT NULL,
   "REQUEST_URL"        VARCHAR2(512 CHAR),
   "REQUEST_METHOD"     VARCHAR2(32 CHAR),
   "CONTROLLER_NAME"    VARCHAR2(256 CHAR),
   "METHOD_NAME"        VARCHAR2(256 CHAR),
   "REQUEST_PARAMS"     CLOB,
   "RESPONSE_RESULT"    CLOB,
   "USER_IP"            VARCHAR2(128 CHAR),
   "USER_AGENT"         VARCHAR2(512 CHAR),
   "EXECUTE_TIME"       NUMBER(10,0),
   "STATUS"             VARCHAR2(32 CHAR),
   "ERROR_MSG"          CLOB,
   "CREATOR"            VARCHAR2(128 CHAR),
   "CREATE_TIME"        TIMESTAMP,
   "UPDATER"            VARCHAR2(128 CHAR),
   "UPDATE_TIME"        TIMESTAMP,
   "DELETED"            NUMBER(1,0) DEFAULT 0,
   CONSTRAINT PK_BUDGET_API_REQUEST_LOG PRIMARY KEY ("ID")
);

PROMPT Done: JASOLAR_BUDGET tables created.
EXIT;
