apiVersion: v1
kind: ConfigMap
metadata:
  name: ja-fsms-fe-config
  namespace: jasolar
data:
  # 前端环境配置
  VITE_GLOB_API_URL: 'http://172.28.49.18:30089' # 后端API地址
  VITE_APP_TITLE: 'JA-FSMS'
  VITE_BASE: '/'
  NODE_ENV: 'development'
